theme: jekyll-theme-minimal
title: Naresh Thakur
logo: "/profile.jpeg?raw=true"
description: >
 <br>
 Passionate about technology, driven by intellectual curiosity!
  <br><br>
  <a href="https://www.linkedin.com/in/thakurinbox/" target="_blank" rel="noreferrer"><img align="right" src="https://raw.githubusercontent.com/thakurinbox/thakurinbox/master/icons/linkedin.svg" alt="icon | LinkedIn" width="40px"/></a><a href="https://medium.com/@thakurinbox" target="_blank" rel="noreferrer"><img align="right" src="https://raw.githubusercontent.com/thakurinbox/thakurinbox/master/icons/medium.svg" alt="icon | Medium" width="40px"/></a>

